runtime: nodejs10
service: frontend

instance_class: F1

handlers:
  - url: /assets
    static_dir: dist/client/
  - url: /.*
    script: auto
    secure: always

env_variables:
  HOST: '0.0.0.0'
  NODE_ENV: 'production'